apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kitamoto-otomatik
  name: $(APP_NAME)
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: nikkinicholasromero/${APP_NAME}:${BUILD_NUMBER}
        ports:
        - containerPort: 80
