apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kitamoto-otomatik
  name: ${APP_NAME}
  labels:
    app: kitamoto-otomatik-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitamoto-otomatik-admin-ui
  template:
    metadata:
      labels:
        app: kitamoto-otomatik-admin-ui
    spec:
      containers:
      - name: ${APP_NAME}
        image: nikkinicholasromero/${APP_NAME}:${BUILD_NUMBER}
        ports:
        - containerPort: 80
