apiVersion: v1
kind: Service
metadata:
  namespace: kitamoto-otomatik
  name: kitamoto-otomatik-admin-ui
  labels:
    app: kitamoto-otomatik-admin-ui
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 80
  selector:
    app: kitamoto-otomatik-admin-ui
