apiVersion: v1
kind: Service
metadata:
  namespace: kitamoto-otomatik
  name: kitamoto-otomatik-admin-ui
  labels:
    app: kitamoto-otomatik-admin-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: kitamoto-otomatik-admin-ui
